// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Persistence;

#nullable disable

namespace Persistence.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Domain.Reservation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("MovieId")
                        .HasColumnType("int");

                    b.Property<int>("SeatNumbers")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("Reservations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2023, 10, 2, 15, 57, 13, 122, DateTimeKind.Local).AddTicks(5538),
                            MovieId = 1,
                            SeatNumbers = 250,
                            UpdatedAt = new DateTime(2023, 10, 2, 15, 57, 13, 122, DateTimeKind.Local).AddTicks(5564)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2023, 10, 2, 15, 57, 13, 122, DateTimeKind.Local).AddTicks(5568),
                            MovieId = 2,
                            SeatNumbers = 250,
                            UpdatedAt = new DateTime(2023, 10, 2, 15, 57, 13, 122, DateTimeKind.Local).AddTicks(5569)
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2023, 10, 2, 15, 57, 13, 122, DateTimeKind.Local).AddTicks(5571),
                            MovieId = 3,
                            SeatNumbers = 250,
                            UpdatedAt = new DateTime(2023, 10, 2, 15, 57, 13, 122, DateTimeKind.Local).AddTicks(5572)
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2023, 10, 2, 15, 57, 13, 122, DateTimeKind.Local).AddTicks(5574),
                            MovieId = 4,
                            SeatNumbers = 250,
                            UpdatedAt = new DateTime(2023, 10, 2, 15, 57, 13, 122, DateTimeKind.Local).AddTicks(5575)
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2023, 10, 2, 15, 57, 13, 122, DateTimeKind.Local).AddTicks(5577),
                            MovieId = 5,
                            SeatNumbers = 250,
                            UpdatedAt = new DateTime(2023, 10, 2, 15, 57, 13, 122, DateTimeKind.Local).AddTicks(5578)
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2023, 10, 2, 15, 57, 13, 122, DateTimeKind.Local).AddTicks(5582),
                            MovieId = 6,
                            SeatNumbers = 250,
                            UpdatedAt = new DateTime(2023, 10, 2, 15, 57, 13, 122, DateTimeKind.Local).AddTicks(5583)
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2023, 10, 2, 15, 57, 13, 122, DateTimeKind.Local).AddTicks(5584),
                            MovieId = 7,
                            SeatNumbers = 250,
                            UpdatedAt = new DateTime(2023, 10, 2, 15, 57, 13, 122, DateTimeKind.Local).AddTicks(5586)
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2023, 10, 2, 15, 57, 13, 122, DateTimeKind.Local).AddTicks(5587),
                            MovieId = 8,
                            SeatNumbers = 250,
                            UpdatedAt = new DateTime(2023, 10, 2, 15, 57, 13, 122, DateTimeKind.Local).AddTicks(5588)
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2023, 10, 2, 15, 57, 13, 122, DateTimeKind.Local).AddTicks(5590),
                            MovieId = 9,
                            SeatNumbers = 250,
                            UpdatedAt = new DateTime(2023, 10, 2, 15, 57, 13, 122, DateTimeKind.Local).AddTicks(5591)
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2023, 10, 2, 15, 57, 13, 122, DateTimeKind.Local).AddTicks(5593),
                            MovieId = 10,
                            SeatNumbers = 250,
                            UpdatedAt = new DateTime(2023, 10, 2, 15, 57, 13, 122, DateTimeKind.Local).AddTicks(5595)
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(2023, 10, 2, 15, 57, 13, 122, DateTimeKind.Local).AddTicks(5596),
                            MovieId = 11,
                            SeatNumbers = 250,
                            UpdatedAt = new DateTime(2023, 10, 2, 15, 57, 13, 122, DateTimeKind.Local).AddTicks(5598)
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = new DateTime(2023, 10, 2, 15, 57, 13, 122, DateTimeKind.Local).AddTicks(5599),
                            MovieId = 12,
                            SeatNumbers = 250,
                            UpdatedAt = new DateTime(2023, 10, 2, 15, 57, 13, 122, DateTimeKind.Local).AddTicks(5600)
                        },
                        new
                        {
                            Id = 13,
                            CreatedAt = new DateTime(2023, 10, 2, 15, 57, 13, 122, DateTimeKind.Local).AddTicks(5602),
                            MovieId = 13,
                            SeatNumbers = 250,
                            UpdatedAt = new DateTime(2023, 10, 2, 15, 57, 13, 122, DateTimeKind.Local).AddTicks(5603)
                        },
                        new
                        {
                            Id = 14,
                            CreatedAt = new DateTime(2023, 10, 2, 15, 57, 13, 122, DateTimeKind.Local).AddTicks(5604),
                            MovieId = 14,
                            SeatNumbers = 250,
                            UpdatedAt = new DateTime(2023, 10, 2, 15, 57, 13, 122, DateTimeKind.Local).AddTicks(5606)
                        },
                        new
                        {
                            Id = 15,
                            CreatedAt = new DateTime(2023, 10, 2, 15, 57, 13, 122, DateTimeKind.Local).AddTicks(5607),
                            MovieId = 15,
                            SeatNumbers = 250,
                            UpdatedAt = new DateTime(2023, 10, 2, 15, 57, 13, 122, DateTimeKind.Local).AddTicks(5608)
                        },
                        new
                        {
                            Id = 16,
                            CreatedAt = new DateTime(2023, 10, 2, 15, 57, 13, 122, DateTimeKind.Local).AddTicks(5610),
                            MovieId = 16,
                            SeatNumbers = 250,
                            UpdatedAt = new DateTime(2023, 10, 2, 15, 57, 13, 122, DateTimeKind.Local).AddTicks(5611)
                        },
                        new
                        {
                            Id = 17,
                            CreatedAt = new DateTime(2023, 10, 2, 15, 57, 13, 122, DateTimeKind.Local).AddTicks(5613),
                            MovieId = 17,
                            SeatNumbers = 250,
                            UpdatedAt = new DateTime(2023, 10, 2, 15, 57, 13, 122, DateTimeKind.Local).AddTicks(5614)
                        },
                        new
                        {
                            Id = 18,
                            CreatedAt = new DateTime(2023, 10, 2, 15, 57, 13, 122, DateTimeKind.Local).AddTicks(5616),
                            MovieId = 18,
                            SeatNumbers = 250,
                            UpdatedAt = new DateTime(2023, 10, 2, 15, 57, 13, 122, DateTimeKind.Local).AddTicks(5617)
                        },
                        new
                        {
                            Id = 19,
                            CreatedAt = new DateTime(2023, 10, 2, 15, 57, 13, 122, DateTimeKind.Local).AddTicks(5619),
                            MovieId = 19,
                            SeatNumbers = 250,
                            UpdatedAt = new DateTime(2023, 10, 2, 15, 57, 13, 122, DateTimeKind.Local).AddTicks(5620)
                        },
                        new
                        {
                            Id = 20,
                            CreatedAt = new DateTime(2023, 10, 2, 15, 57, 13, 122, DateTimeKind.Local).AddTicks(5622),
                            MovieId = 20,
                            SeatNumbers = 250,
                            UpdatedAt = new DateTime(2023, 10, 2, 15, 57, 13, 122, DateTimeKind.Local).AddTicks(5623)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
